#!/bin/bash

function processor {
	MODEL=$(cat /proc/cpuinfo | grep "model name" | sort -u | cut -d: -f2)
	N_NUMBER=$(cat /proc/cpuinfo | grep "siblings" | sort -u | cut -d: -f2)
	CACHE=$(cat /proc/cpuinfo | grep "cache size" | sort -u | cut -d: -f2)
	ARCHITECTURE=$(uname -m)
	VIRTUALIZATION='No'
	if grep "vmx" /proc/cpuinfo > /dev/null
	then
		VIRTUALIZATION='Yes'
	fi
	if grep "svm" /proc/cpuinfo > /dev/null
	then
		VIRTUALIZATION='Yes'
	fi
	
	echo processor
	echo -e "Modelo:\t"$MODEL
	echo -e "Número de Núcleos:\t"$N_NUMBER
	echo -e "Memoria caché:\t"$CACHE
	echo -e "Arquitectura del procesador:\t"$ARCHITECTURE 
	echo -e "¿Soporta Virtualización:\t"$VIRTUALIZATION
}

function memory {
	RAM=$(grep "MemTotal" /proc/meminfo | cut -d: -f2)
	SWAP=$(grep "SwapTotal" /proc/meminfo | cut -d: -f2)
	FREE_RAM=$(grep "MemFree" /proc/meminfo | cut -d: -f2)
	FREE_SWAP=$(grep "SwapFree" /proc/meminfo | cut -d: -f2)
	
	echo memory
	echo -e "Memoria Total:\t"$RAM
	echo -e "Swap Total:\t"$SWAP
	echo -e "Memoria Libre:\t"$FREE_RAM
	echo -e "Swap Libre:\t"$FREE_SWAP
}


function newtcrk {
	IFS=$'\n'	
	NET=($(lspci | egrep -i 'network|ethernet'))
	unset IFS
	
	echo "newtcrk"
	for n in "${NET[@]}"
	do 
		echo ${n##*:}
		
	done
}

function os {
	OS=$(uname)
	KERNEL=$(uname -r)
	
	echo -e "Sistema Operativo:\t" $OS
	echo -e "Version de Kernel:\t" $KERNEL
}
 os


